name: Build & Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nodejs app
        uses: actions/checkout@v2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script:
            cd /var/www/html
            git clone https://github.com/marcelniyi/tutorial.git
            echo 'Deployment successful to digitalocean'
